name: PR lint

on:
  pull_request:
    paths:
      - '**.py'
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - 'scripts/tvm_cli/Dockerfile.amd64'
      - 'scripts/tvm_cli/Dockerfile.arm64'
      - '**.sh'

jobs:
  linting:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip cppcheck shellcheck
          pip install pylint

      - name: python-lint
        id: python
        run: |
          find . -name "*.py" | xargs pylint \
            --disable=import-error \
            --disable=invalid-name \
            --disable=missing-module-docstring \
            --disable=redefined-builtin \
            --disable=too-many-locals \
            --disable=too-many-statements \
            --disable=broad-except \
            --disable=consider-using-sys-exit

      - name: cpp-lint
        id: cpp
        run: |
          cppcheck --enable=all --suppress=missingIncludeSystem .

      - name: dockerfile-lint
        id: dockerfile
        uses: jbergstroem/hadolint-gh-action@v1.9.1
        with:
          dockerfile: "scripts/tvm_cli/Dockerfile.amd64 scripts/tvm_cli/Dockerfile.arm64"

      - name: shell-lint
        id: shell
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck --shell=bash
        shell: sh

      - name: Check failures
        if: steps.python.outcome != 'success' || steps.cpp.outcome != 'success' || steps.dockerfile.outcome != 'success' || steps.shell.outcome != 'success'
        run: exit 1

  test:
    runs-on: ARM64
    steps:
      - name: Test
        run: |
          df
          docker system df -v
