name: Contribution pull requests validation

on:
  pull_request:

jobs:

  tvm-cli-validate:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, ARM64]

      container:
        image: autoware/model-zoo-tvm-cli:bleedingedge

      steps:

        - name: Install LFS
          run: |
            apt-get update
            apt-get install git-lfs

        - name: Checkout
          uses: actions/checkout@v2
          with:
            lfs: true

        - name: tvm_cli test
          run: |
            cp -r . /tmp
            cd /tmp
            ./scripts/tvm_cli/tvm_cli.py test
