name: Contribution pull requests validation

on:
  pull_request:

jobs:

  tvm-cli-validate:

      runs-on: ubuntu-latest

      container:
        image: autoware/model-zoo-tvm-cli:bleedingedge

      steps:

        - name: Checkout
          uses: actions/checkout@v1
          with:
            lfs: true

        - name: tvm_cli test
          run: |
            cp -r . /tmp
            ./scripts/tvm_cli/tvm_cli.py test
