name: Models compile and upload

on:
  workflow_call:
    inputs:
      tag_name:
        required: false
        default: 'latest'
        type: string
    secrets:
      MODELZOO_S3_ID:
        required: true
      MODELZOO_S3_KEY:
        required: true

jobs:
  compile-push-bucket:
    strategy:
      matrix:
        os: [ubuntu-latest, ARM64]
    runs-on: ${{ matrix.os }}
    container:
      image: autoware/model-zoo-tvm-cli:${{ inputs.tag_name }}
    steps:
      - name: Install LFS
        run: |
          apt-get update
          apt-get install git-lfs

      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Generate and save artifacts
        env:
          AWS_S3_BUCKET: autoware-modelzoo
          AWS_ACCESS_KEY_ID: ${{ secrets.MODELZOO_S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MODELZOO_S3_KEY }}
          AWS_REGION: us-east-2
        run: |
          cp -r . /tmp
          cd /tmp
          ./scripts/tvm_cli/tvm_cli.py test
          tar -C /tmp/neural_networks/`uname -m` \
            -czf networks-`uname -m`.tar.gz .
          md5sum networks-`uname -m`.tar.gz | cut -d ' ' -f 1 >> networks-`uname -m`.md5
          pip install --quiet --no-cache-dir awscli==1.19.98
          aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
          ${AWS_ACCESS_KEY_ID}
          ${AWS_SECRET_ACCESS_KEY}
          ${AWS_REGION}
          text
          EOF
          aws s3 cp . s3://autoware-modelzoo/ \
            --recursive --exclude "*" \
            --include "networks-`uname -m`.tar.gz" \
            --include "networks-`uname -m`.md5" \
            --profile s3-sync-action --acl public-read
          aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
          null
          null
          null
          text
          EOF
