name: Docker image building

on:
  workflow_call:
    inputs:
      image_name:
        required: false
        default: 'autoware/model-zoo-tvm-cli'
        type: string
      tag_name:
        required: false
        default: 'latest'
        type: string
    secrets:
      DKR_USR:
        required: true
      DKR_PASS:
        required: true

jobs:
  docker-build-push:
    strategy:
      matrix:
        os: [ubuntu-latest, ARM64]
        name: [no-cuda, cuda]
        include:
        - os: ubuntu-latest
          arch: amd64
        - os: ARM64
          arch: arm64
        - name: no-cuda
          extra-params: ""
          tag-suffix: ""
        - name: cuda
          extra-params: -c
          tag-suffix: -cuda
    runs-on: ${{ matrix.os }}
    env:
      IMAGE_NAME: ${{ inputs.image_name }}
      TAG_NAME: ${{ inputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Image build and push
        run: |
          docker login -u "${{ secrets.DKR_USR }}" -p "${{ secrets.DKR_PASS }}"
          ./scripts/tvm_cli/build.sh -i "$IMAGE_NAME" -t "$TAG_NAME${{ matrix.tag-suffix }}-${{ matrix.arch }}" --ci ${{ matrix.extra-params }}
          docker push $IMAGE_NAME:$TAG_NAME${{ matrix.tag-suffix }}-${{ matrix.arch }}

      - name: Docker logout
        if: ${{ always() }}
        run: docker logout
