name: Models compile and upload

on:
  workflow_call:
    inputs:
      tag_name:
        required: false
        default: 'latest'
        type: string
      version_name:
        required: false
        default: 'latest'
        type: string
    secrets:
      MODELZOO_S3_ID:
        required: true
      MODELZOO_S3_KEY:
        required: true

jobs:
  compile-push-bucket:
    strategy:
      matrix:
        os: [ubuntu-latest, ARM64]
    runs-on: ${{ matrix.os }}
    container:
      image: autoware/model-zoo-tvm-cli:${{ inputs.tag_name }}
    steps:
      - name: Install LFS
        run: |
          apt-get update
          apt-get install git-lfs

      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Generate and save artifacts
        env:
          AWS_S3_BUCKET: autoware-modelzoo
          AWS_ACCESS_KEY_ID: ${{ secrets.MODELZOO_S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MODELZOO_S3_KEY }}
          AWS_REGION: us-east-2
        run: |
          git config --global --add safe.directory $(pwd)
          git lfs pull
          cp -r . /tmp/modelzoo
          cd /tmp/modelzoo
          rm -rf neural_networks/
          ./scripts/tvm_cli/tvm_cli.py test
          find neural_networks/ -maxdepth 1 -mindepth 1 -type d -execdir tar -C {} -czf {}-${{ inputs.version_name }}.tar.gz . \;
          find neural_networks/ -maxdepth 1 -mindepth 1 -type d -execdir bash -c 'md5sum "$1".tar.gz | cut -d ' ' -f 1 > "$1.md5"' _ {}-${{ inputs.version_name }} \;
          find neural_networks/ -maxdepth 1 -mindepth 1 -type d -execdir bash -c 'basename "$1" >> index-$(uname -m)' _ {} \;
          sort -o neural_networks/index-$(uname -m) neural_networks/index-$(uname -m)
          pip install --quiet --no-cache-dir awscli==1.19.98
          aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
          ${AWS_ACCESS_KEY_ID}
          ${AWS_SECRET_ACCESS_KEY}
          ${AWS_REGION}
          text
          EOF
          aws s3 cp neural_networks/ s3://autoware-modelzoo/models/${{ inputs.version_name }}/ \
            --recursive --exclude "*" \
            --include "*.tar.gz" \
            --include "*.md5" \
            --include "index-*" \
            --profile s3-sync-action --acl public-read
          aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
          null
          null
          null
          text
          EOF
